### ISSUE TITLE
peer to peer code reveiew

### ISSUE THREAD

**Issue by divinecharlotte** [bobb-Rob/Leardership-board#4]
hi @bobb-Rob,
your project is working well and it has a good styling good job so far 👏 
but there is something you still have to work on so that your project may look perfect
### required changes 
- when you add a new name and score they appear when we click the refresh button please try to make the new input appear on the page load

**Comment by bobb-Rob** [comment]
@divinecharlotte Thank you for this. I fixed the issue.
